name: CICD Docker Github Action
on:
  push:
    branches:
      - master

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: listing files
        run: ls -la

      # - name: Setup Golang on Runners
      #   uses: actions/setup-go@v4
      #   with:
      #     go-version: '1.22'

      - name: Check Go version
        run: go version

      - name: Test Code
        run: go test -v ./...